### ISSUE TITLE
Negative scoring for missed days

### ISSUE THREAD

**Issue by abers** [eshapard/AnkiHabitica#129]
Unsure how easy this would be to implement, but it'd be good to also optionally have negative consequences for missing days - or similar. Could add a binary flag in config for enabling it, as well as a multiplier for how harshly (or not) to treat each missed day.

**Comment by 71e6fd52** [comment]
If you didn't open the Anki, how does Anki know you miss a day.

**Comment by eshapard** [comment]
It's been a long time since I've been involved with the code, but I 
think this should be possible if you check the review table for gaps of 
24 hours or more between reviews.

Personally, I don't think this is a good idea. I think you should make 
studying as positive as possible and reward yourself, but not punish 
yourself.

Excerpts from 71e6fd52's message of March 31, 2022 11:12 pm:
