### ISSUE TITLE
The add on don't work

### ISSUE THREAD

**Issue by MrRafaelSantos** [eshapard/AnkiHabitica#19]
Hi,
After configuration the following error appears:

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\rafael\Documents\Anki\addons\ankihabitica.py", line 621, in score_backlog
    ah.habitica.grab_scorecounter('Anki Points')
  File "C:\Users\rafael\Documents\Anki\addons\AnkiHabitica\habitica_class.py", line 332, in grab_scorecounter
    if self.missing[habit]: 
KeyError: 'Anki Points'

**Comment by eshapard** [comment]
Try creating a habit called Anki Points in habitica.

**Comment by eshapard** [comment]
OK, I'm pretty sure I know what the problem is.

This is probably caused by the check_db_on_profile_load setting being set to True by default.

Having it set to True is fine once everything the habit has been set up on Habitica, but causes problems otherwise.

I'll change the default setting to False and re-upload to ankiweb.

**Comment by eshapard** [comment]
OK, seems that to recreate this problem you have to start with a fresh profile (nothing in the config file), set it up, and then instead of studying cards from a deck, restart Anki.

You then get the error message as ankihabitica attempts to run the check_db_on_profile_load routines, but then the habit is created and the addon seems to run fine after that.

There's probably a way to abort the check_db_on_profile_load if the key is missing, but as this causes a very minor problem, I'm not in a hurry to make that change. I'll keep this issue open and possibly make the fix later.

I'm assuming the OP has discovered that everything is working fine.
