### ISSUE TITLE
Can only handle ascii symbols in profile name

### ISSUE THREAD

**Issue by haidbz** [eshapard/AnkiHabitica#20]
Not a big problem, as it is a small matter to change profile name to something that does not include special letters like æøå, but slightly annoying to those whom it may concern.

**Comment by twilsonco** [comment]
This could be fixed by using a unicode configuration file for the add-on. It's relatively simple since you can just write the configuration dict to the file as a unicode string and everything will be preserved, then read the config file back in as a unicode string and evaluate it with `ast.literal_eval()` (this prevents code from being executed and only evaluates literals, such as reading a python list or dict. If code needs to be executed then `eval()` can be used, but there is a risk of running malicious code.) to convert it back into a python dict.

**Comment by eshapard** [comment]
Hmm... yes. There are some complications with the version of python shipped with Anki, file formats, and utf-8. I hadn't considered non-ascii profile names; probably 99% of users just use the default 'User 1'.

There's probably a fix for this. We might have to explicitly declare the profile name to be utf-8.

I'll keep this on the back-burner.

Here's a shot in the dark... in the config file (AnkiHabitica subdirectory) try putting a u outside the quotes around a profile name as in u'profilename'.... I believe that will mark the profilename as unicode/utf-8.

**Comment by eshapard** [comment]
Tim, if you want to play with this and try to get the config file to save
unicode values correctly, be my guest. :-)

**Comment by eshapard** [comment]
Github user aleadag has found the solution. It was basically what I mentioned in my Aug 31st post, (set profilename as explicitly unicode u'profilename') with another complication that had to be fixed.

I haven't tested this, but I did merge the proposed changes, so the current version on github should work.

I'll update the ankiweb version later.
