### ISSUE TITLE
Great addon, but too slow

### ISSUE THREAD

**Issue by Yutsuten** [eshapard/AnkiHabitica#27]
Everything is working great, but it is terribly slow between a card and another...
It takes about 1~2 seconds, and it is a lot compared to instant card change - the default without the addon.
I've set _show_mini_stats_, _show_popup_ and _keep_log_ to false, but I didn't noticed any performance improvement.

Please optimize the addon, I'd love continue using it, but the delay slows me down.

**Comment by twilsonco** [comment]
Do you have a large collection (large number of decks/notes/cards)?

**Comment by mateus-etto** [comment]
I have 3 decks with about 14.000 cards on all of them. The deck I was testing the addon have almost 11.000 cards.

**Comment by twilsonco** [comment]
I have a ~0.25 second delay between cards and my collection is over 45k cards, so I'm not entirely sure what is causing the issue for you. Reviewing the code, however, I found one potential place to optimize the sqlite queries. Currently the entire collection is queried between cards, though only the current deck needs to be queried. 
I'm not an expert on sql, however. On the one hand, we're searching through a subset of the collection, so it may require less work. On the other hand, this just adds another condition to the sqlite query, which may slow things down...
Another option might be to revive the event/hook-based recording (for everything but "decks completed", at least) since most of the stats that the add-on fetches can be reliably obtained using only internal Anki events.
I'll look into this once I get my overpriced POS Macbook Pro back from Apple. Should be any day now... Third time they've replaced SSD+Logic board (CPU+GPU+RAM) to try and fix it. Third time's a charm, maybe? Or maybe Apple sucks now, as shown by the new Macbook Pro that's obviously designed for non-"pro" users...

**Comment by mateus-etto** [comment]
Oh I see...
Let me give a more complete information about my Anki's collection:

- 3 decks
- 14.043 cards
- 7 note types (all notes have cards, but 3 are unused - not in a deck)
- My decks are for studying Japanese, so I extensively use Japanese characters.
- There are images on some cards (sometimes in a field only for images, sometimes mixed with text).
- Each card note have 4~5 fields
- A review session have about 500 cards.

If there is any other relevant information, please tell me.
Thank you for the fast reply.

**Comment by twilsonco** [comment]
Can you post your machine specs?

**Comment by mateus-etto** [comment]
I'm on Windows 10
Processor: Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
Memory (RAM): 8.00GB
System Type: 64-bits

Is this enough?

**Comment by mateus-etto** [comment]
Here's my collection, this may help:
https://www.dropbox.com/s/4peajzfkg72nfdp/collection.apkg?dl=0
I exported all my decks into this file, so you may create a new profile, import the package and make the tests.

**Comment by twilsonco** [comment]
No reason I can think of why it should be going so slow on your machine with 14k cards. Best solution is probably to use event-driven logging of stats. I'll look into this once I have my machine back. I'll update this thread when I finish.

**Comment by eshapard** [comment]
There is a logging feature that can be turned on. It creates a log file that might give us some info about which functions are taking the most time.

From what I remember, the reviews database doesn't contain any deck information (could be wrong about that), so narrowing some of the searches to the current deck would probably slow that function down.

You get points for several different things (write answers, wrong answers, completed decks, etc.). My guess is that the more complicated operation of counting completed decks might be what's slowing it down here.

It's possible to award 0 points for completing decks... I don't remember if this will stop the program from checking for this.

If the log file doesn't clear anything up, then what we might want to do is to find the function that calculates the score, and disable some of the functions; then maybe add them back one at a time.

If I didn't think to do this originally, it should be pretty simple to change the code to disable score components by setting their point worth to 0.

**Comment by mateus-etto** [comment]
I have dual boot with Ubuntu, so I can take the log there too.
Even in Ubuntu, it is taking about 0.8 seconds between cards.
This is the Log file in Ubuntu: https://www.dropbox.com/s/55stw8y9goi9kyp/AnkiHabitica-ubuntu.log?dl=0

**Comment by eshapard** [comment]
0.8 seconds sounds fine to me. That's about the same lag I have.

**Comment by mateus-etto** [comment]
"_0.8 seconds sounds fine to me. That's about the same lag I have._"

Does this mean that **no** code will be improved?
If "yes", I'll drop my hopes and won't use it... In my opinion, all its great features are killed by the bad performance...
Feel free to ignore my opinion, of course.

**Comment by twilsonco** [comment]
Like I said, 
> I'll look into this once I have my machine back. I'll update this thread when I finish.
In the meantime, those seconds probably won't add up to anything significant. If you have cards that take you less than 0.8 seconds to answer correctly, then I'd say you don't need to review those cards as you already seem to know them quite well.
If you decide not to use this free add-on that's one of the best developed add-ons for Anki, we understand.

**Comment by eshapard** [comment]
Mateus,

Do you know any python? Are you willing to learn?

You could adjust the code yourself, so that some of the scoring routines
are ignored. This would allow you to simplify how you are scored in order
gain speed of execution.

I pretty much lay out what you need to do in the Edit of a previous post.

This would involve only adding simple 'if' statements and the experience
might lead to useful skills down the line if you decide to learn more
programming skills. Python is a good language to start with.

Here's something to get you started.

Find the calculate_db_score function in the code.

change the line:

dbdecks = int(AnkiHabitica.db_helper.decks_count(start_date) *
ah.settings.deckpoints

to

if ah.settings.deckpoints:
    dbdecks = int(AnkiHabitica.db_helper.decks_count(start_date) *
ah.settings.deckpoints
else:
    dbdecks = 0



*note, the line spacing is important. You want the if and else lined up
with the other lines, but the dbdecks statements to be indented a further 4
spaces.

Now set deckpoints equal to 0 in the settings at the top of the addon...
now it will skip over the step where it scans the database for how many
decks you completed. This is probably one of the checks that takes the
longest.

**Comment by mateus-etto** [comment]
I know the addon is done by volunteers, sorry if I said anything rude.
The features are great, but with the delay I loss my review flow.

When creating this issue, I was just asking myself: "_wouldn't be faster if everything were done on memory, and only make disk access when needed?_", but looks like everything is much more complex than it looks.

Eshapard, thank you for inviting me to help coding, but unfortunately I don't have time to help. I'm here as a user giving feedback, not as a programmer. Sorry.

Feel free to close the issue.
Thank you for the attention.

**Comment by eshapard** [comment]
The database queries are done entirely in memory. Unless your operating
system is running out of memory and has to use disk space, it's all done in
RAM... But these database queries do still take a fraction of a second.

That's the nature of the beast. Anki's database was set up for Anki's use;
not to track points for Habitica; so we have to do some complicated
procedures in order to get that kind of information out of the database.

**Comment by mateus-etto** [comment]
Oh, I see... Pretty complicated.
Just by making it work you did a great job.

I don't know Python, but is multi-threading something feasible? (just giving the idea...)
Or maybe something easier: only updating the data after X answers (user defined in the options, Default is X = 1). This option is something that I would certainly use.

**Comment by eshapard** [comment]
I guess I never posted it here. I did update the code. You can now turn off database checks for items by setting their value to 0 when you edit the addon.
