### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by alarswilson** [eshapard/AnkiHabitica#29]
Traceback (most recent call last):
  File "aqt/main.pyc", line 629, in keyPressEvent
  File "aqt/reviewer.pyc", line 313, in _keyHandler
  File "aqt/reviewer.pyc", line 271, in _answerCard
  File "anki/hooks.pyc", line 58, in repl
  File "/Users/alw/Documents/Anki/addons/ankihabitica.py", line 545, in hrpg_realtime
    if compare_score_to_db():
  File "/Users/alw/Documents/Anki/addons/ankihabitica.py", line 349, in compare_score_to_db
    ah.config[ah.settings.profile]['oldscore'] = ah.config[ah.settings.profile]['score'] # Capture old score
KeyError: 'score'

**Comment by eshapard** [comment]
Looks like you didn't have a score in your config file... if everything else is working correctly, this should take care of itself as you use the addon and earn points. Has this resolved itself.

**Comment by alarswilson** [comment]
It wouldn't do anything. I had to uninstall the plugin.

**Comment by okkes** [comment]
I had this problem as well. The problem was solved by simply restarting Anki again.
(I can't assure you whether anything else after this steps works fully and correctly since I have yet to find out the things I can do with this plugin)

The steps:
- install plugin
- close Anki, and then start the Anki again 
- try to learn a deck, you should see the error @alarswilson  posted,
- try out a few other options to keep seeing the same error
- sync and quit anki, and then restart Anki again. (repeat this steps if necessary)

**Comment by eshapard** [comment]
okkes, If those are the steps you took, you don't seem to have set up the addon... go to Tools >> AnkiHabitica >> Setup Anki Habitica

**Comment by okkes** [comment]
If by setting up the addon means inserting the token and psw thing, then yes, I did that already. I did however forgot to mention that in my steps, my bad for that.
