### ISSUE TITLE
Thanks for this great addon, but i've got a problem

### ISSUE THREAD

**Issue by xiaoyou711** [eshapard/AnkiHabitica#30]
since yesterday there was problem when I tried to refresh the anki avatar. the information is:

Unhandled exception in thread started by <bound method Habitica.save_avatar of <AnkiHabitica.habitica_class.Habitica object at 0x03825750>>

I tried to reinstall the add-on and anki, but it didn't work and that's really a little bothering. I wonder if you can give me some helpful information,

Thank you very much!

**Comment by xiaoyou711** [comment]
i have changed one "true" into "false" (forgotten which one) and it runs good now. although there is a error information, but it does works..
so happy and still very thankful that you make the so great addon!
:+1:

**Comment by eshapard** [comment]
Hmm... not sure what the problem was. I haven't seen it before. 

If you really want to track this down, you might try finding the setting that controls threading. If you turn that off, you'll get a more detailed error message about what's going wrong. The one you got just says that the thread died, but it doesn't give any details.

**Comment by victorjatoba** [comment]
I'm have the same error:

"An error occurred. It may have been caused by a harmless bug, 
or your deck may have a problem. 

To confirm it's not a problem with your deck, please run Tools > Check Database. 
If that doesn't fix the problem, please copy the following
into a bug report:

Unhandled exception in thread started by <bound method Habitica.save_avatar of <AnkiHabitica.habitica_class.Habitica object at 0x2fdba50>>"

It's occur always when I try to open the desktop version or select "Refresh Habitica Avatar" option

SO: Ubuntu 16.04 LTS 64-bit

**Comment by eshapard** [comment]
Hmm... I have the same platform (ubuntu 16.04) and I'm not seeing this error.

Something's going wrong when it tries to fetch the avatar.... 

It says it's unable to load the library icui18n.  Maybe try a `sudo apt-get install libicu48`?

**Comment by eshapard** [comment]
Does it seem to work otherwise?

**Comment by victorjatoba** [comment]
`sudo apt-get install libicu48`?
I putted this command in terminal and was showed this message: "Unable to locate package libicu48"

I see that the error: "Unable to load library icui18n "Cannot load library icui18n: (libicui18n.so.48: cannot open shared object file: No such file or directory)" is not correlated with your add-on. Because after I removed the Anki Habitica add-on I received the same error above.

The really error about your add-on showed is: "Unhandled exception in thread started by <bound method Habitica.save_avatar of <AnkiHabitica.habitica_class.Habitica object at 0x2876a10>>"

Another suggestion to solve the problem?

Thanks!

**Comment by eshapard** [comment]
Ok, well with threading, we don't get much of an error message; python just tells us that the thread died.

So let's turn off threading and we should get a better error message.

Edit the habitica_class.py file in the AnkiHabitica subdirectory in the addons directory.

On line 16, change allow_threads from True to False.

Save and fire up Anki again and you should get a more detailed error message.

BTW: Is the addon working despite this error? What is your profile name? Is it the default 'User 1'?

**Comment by eshapard** [comment]
I made some changes to the version on github. Hopefully, this will fix the problem.

The addon had trouble saving the avatar image using certain unicode characters, so I changed it to use the habitica user ID instead of the profile name.
