### ISSUE TITLE
Way to use old version?

### ISSUE THREAD

**Issue by smh020** [eshapard/AnkiHabitica#33]
Is this version of anki habitica working?

https://ankiweb.net/shared/info/1349714377

I remember using it for a while before it stopped working.

**Comment by eshapard** [comment]
yes, the one on ankiweb should work

On Dec 29, 2016 3:24 PM, "smh020" <notifications@github.com> wrote:

Is this version of anki habitica working?

https://ankiweb.net/shared/info/1349714377

I remember using it for a while before it stopped working.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/eshapard/AnkiHabitica/issues/33>, or mute the thread

**Comment by eshapard** [comment]
Just checked the link... that's not my addon.

No, the 'Habitica Support (Improved AnkiHRPG)' no longer works. It was never updated to v3 of the Habitica API.
