### ISSUE TITLE
A question about the habit created in Habitica

### ISSUE THREAD

**Issue by AmodeusR** [eshapard/AnkiHabitica#84]
So, the Addon creates automatically the Habit in Habitica, but it has a name and a code written in the description. Can be those changed? Can I change the title and take out the code from the description or it wouldn't work?

**Comment by eshapard** [comment]
If you change the code inside, you'll mess it up. Once it's set up and 
working, you might be able to change the title and get away wit that. I 
think it stores the habit ID in a config file, so the addon can find it
even if the title doesn't match.

The problem is that if the config file is ever lost, then the addon will
not be able to find the habit and will create a new habit.

BTW: The code in the habit description is where the addon stores 
important information about your score progress. It's stored on habitica 
so that if you run the addon on any other computers, they can fetch and 
update that code too.

Excerpts from Ricardo Magalhães's message of November 21, 2019 5:57 am:

**Comment by 71e6fd52** [comment]
> The problem is that if the config file is ever lost, then the addon will
> not be able to find the habit and will create a new habit.

If you change `habit` in the config to your custom title, it will work properly, and I recommend you do so.
